# Generated by Django 4.2 on 2023-04-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'customer_tb',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'db_table': 'seller_tb',
            },
        ),
    ]
