# Generated by Django 4.2 on 2023-04-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('zipcode', models.CharField(max_length=30)),
                ('location', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'customer_tb',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=30)),
                ('location', models.CharField(default='', max_length=30)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'db_table': 'seller_tb',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=30)),
                ('ingredients_used', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product/')),
                ('status', models.CharField(default='available', max_length=30)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeBake.seller')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeBake.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeBake.product')),
            ],
            options={
                'db_table': 'cart_tb',
            },
        ),
    ]
