# Generated by Django 4.2 on 2023-04-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_date',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='order_placed', max_length=20),
        ),
    ]
