# Generated by Django 4.2 on 2023-04-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBake', '0005_customercontact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
