# Generated by Django 4.2 on 2023-04-22 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBake', '0006_alter_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_date',
            field=models.CharField(default=datetime.date.today, max_length=30),
        ),
    ]
