# Generated by Django 4.2 on 2023-04-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBake', '0008_alter_cart_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='admin@123', max_length=30)),
                ('password', models.CharField(default='admin', max_length=50)),
            ],
            options={
                'db_table': 'admin_tb',
            },
        ),
    ]
