# Generated by Django 4.2.3 on 2023-07-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBake', '0010_alter_customer_password_alter_seller_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='latitude',
            field=models.FloatField(default=''),
        ),
        migrations.AddField(
            model_name='seller',
            name='longitude',
            field=models.FloatField(default=''),
        ),
    ]
