# Generated by Django 4.2 on 2023-07-22 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBake', '0011_seller_latitude_seller_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='longitude',
            new_name='long',
        ),
    ]
