# Generated by Django 4.2.3 on 2023-07-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBake', '0011_seller_latitude_seller_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='seller',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
