# Generated by Django 4.2 on 2023-07-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBake', '0012_rename_latitude_seller_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='long',
        ),
        migrations.AddField(
            model_name='seller',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
