# Generated by Django 4.2 on 2023-07-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBake', '0012_alter_seller_latitude_alter_seller_longitude'),
        ('HomeBake', '0013_remove_seller_lat_remove_seller_long_seller_latitude_and_more'),
    ]

    operations = [
    ]
